### ISSUE TITLE
Access Mailchimp API via Reverse Proxy

### ISSUE THREAD

**Issue by SJGodwin** [isisbusapps/mailing-list-client#44]
Currently calls to mailchimp's api are made directly from this library, and thus go from the hosting machine of the containing application to the server hosting mailchimps api. This is an issue, as for example, the current server hosting UOWS is on fitbaweb1 which is within the DMZ, and doesn't have an allowed connection, as of writing this issue, to mailchimps api server. So, calls from UOWS to mailchimp have not been going through. Whereas these calls should be going via the reverse proxy, where we typically allow external connections.

**Comment by SJGodwin** [comment]
Raise a ticket, referencing policy ID 1753, to close the firewall rule between fitbaweb1 and mailchimp once this work has been integrated with prod UOWS.

**Comment by KashDev00** [comment]
The reverse proxy has already been configured to access mailchimp.

https://github.com/isisbusapps/fba-reverse-proxy/blob/0aa3491e4980fed9f20cabe4a72eeae7173ae390/Apache24/conf/stfc/dev.conf#L66

https://github.com/isisbusapps/fba-reverse-proxy/blob/0aa3491e4980fed9f20cabe4a72eeae7173ae390/Apache24/conf/stfc/internalApiProxy-vhosts.conf#L149
